# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181101_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(max_length=10),
        ),
    ]
